version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iata"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ptmgddzv6tsg"
s3_prefix = "iata"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
